name: CI/CD Innovatech EP3 - ECS Fargate
on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: innovatech-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/innovatech-frontend:latest

      - name: Build y Push Backend Ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/innovatech-ventas:latest

      - name: Build y Push Backend Despachos
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/innovatech-despachos:latest

      - name: Forzar nuevo despliegue - Frontend
        run: aws ecs update-service --cluster $ECS_CLUSTER --service frontend-service --force-new-deployment --region $AWS_REGION

      - name: Forzar nuevo despliegue - Ventas
        run: aws ecs update-service --cluster $ECS_CLUSTER --service ventas-service --force-new-deployment --region $AWS_REGION

      - name: Forzar nuevo despliegue - Despachos
        run: aws ecs update-service --cluster $ECS_CLUSTER --service despachos-service --force-new-deployment --region $AWS_REGION
