name: CI/CD Innovatech EP2

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest

      - name: Build y Push Backend Ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-ventas:latest

      - name: Build y Push Backend Despachos
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-despachos:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/innovatech
            docker compose pull
            docker compose up -d --remove-orphans